version: '3'
services:
  server:
    container_name: utl-server-dev
    build:
        context: ./server
    ports:
     - "3001:3001"
    links:
      - mysql
    restart: always
    environment:
      DB: utl
      DB_USER: user
      DB_PWD: pwd
      DB_HOST: mysql
    volumes:
      - ./server:/server
      - /server/node_modules
    command: node /server/index.js

  client:
    container_name: utl-client-dev
    build:
        context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    environment:
      SOCKET: "localhost:3001"
    command: yarn start:dev

  phpmyadmin:
    container_name: utl-phpmyadmin-dev
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'

  mysql:
    container_name: utl-mysql-dev
    image: mysql:5.7.24
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
      MYSQL_DATABASE: utl
    restart: always

volumes:
  db_data:
